In [43]:
import pandas as pd
from sklearn.model_selection import train_test_split
df=pd.read_csv("parkinsons2.csv")
X1=df.drop(columns="status",axis=1)
Y=df[['status']]


In [44]:
Y=df[["status"]]

In [45]:
Y.status.unique()

array([1, 0], dtype=int64)

In [46]:
Y1=Y.replace([0,1],[1,2])

In [47]:
x_tr,x_te,y_tr,y_te=train_test_split(X1,Y1,test_size=0.2,random_state=0)

In [48]:
y_te

status
83        2
12        2
33        1
113       2
171       1
134       2
163       2
124       2
74        2
18        2
7         2
5         2
125       2
161       2
170       1
181       2
123       2
60        1
44        1
141       2
56        2
173       1
136       2
89        2
63        1
55        2
110       2
166       1
175       1
45        1
22        2
155       2
66        2
37        2
4         2
80        2
178       2
106       2
160       2

In [49]:
# One-hot encode the data using pandas get_dummies
features = pd.get_dummies(X1)
# Display the first 5 rows of the last 12 columns
features.iloc[:,5:].head(5)

MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  MDVP:Shimmer(dB)  \
0   0.00370   0.00554     0.01109       0.04374             0.426   
1   0.00465   0.00696     0.01394       0.06134             0.626   
2   0.00544   0.00781     0.01633       0.05233             0.482   
3   0.00502   0.00698     0.01505       0.05492             0.517   
4   0.00655   0.00908     0.01966       0.06425             0.584   

   Shimmer:APQ3  Shimmer:APQ5  MDVP:APQ  Shimmer:DDA      NHR     HNR  \
0       0.02182       0.03130   0.02971      0.06545  0.02211  21.033   
1       0.03134       0.04518   0.04368      0.09403  0.01929  19.085   
2       0.02757       0.03858   0.03590      0.08270  0.01309  20.651   
3       0.02924       0.04005   0.03772      0.08771  0.01353  20.644   
4       0.03490       0.04825   0.04465      0.10470  0.01767  19.649   

       RPDE       DFA   spread1   spread2        D2       PPE  
0  0.414783  0.815285 -4.813031  0.266482  2.301442  0.284654  
1  0.458359  0.819521 -4.075192  0.335590  2.486855  0.368674  
2  0.429895  0.825288 -4.443179  0.311173  2.342259  0.332634  
3  0.434969  0.819235 -4.117501  0.334147  2.405554  0.368975  
4  0.417356  0.823484 -3.747787  0.234513  2.332180  0.410335

In [50]:
# Use numpy to convert to arrays
import numpy as np
# Labels are the values we want to predict
labels = np.array(Y1['status'])
# Remove the labels from the features
# axis 1 refers to the columns
features= X1
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

In [51]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [52]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)


Training Features Shape: (146, 22)
Training Labels Shape: (146,)
Testing Features Shape: (49, 22)
Testing Labels Shape: (49,)


In [53]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [54]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')


Mean Absolute Error: 0.13 degrees.


In [55]:
errors

array([0.002, 0.039, 0.004, 0.057, 0.015, 0.109, 0.007, 0.169, 0.07 ,
       0.399, 0.798, 0.   , 0.02 , 0.003, 0.002, 0.048, 0.062, 0.49 ,
       0.575, 0.324, 0.03 , 0.253, 0.   , 0.023, 0.   , 0.065, 0.   ,
       0.084, 0.191, 0.001, 0.16 , 0.104, 0.035, 0.227, 0.029, 0.027,
       0.   , 0.934, 0.085, 0.03 , 0.001, 0.027, 0.02 , 0.   , 0.003,
       0.009, 0.197, 0.741, 0.056])

In [56]:
test_labels

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 1], dtype=int64)

In [57]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors/ test_labels)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 89.48 %.


In [58]:
len(test_labels)

49

In [59]:
len(predictions)

49

In [60]:
predictions

array([1.998, 1.961, 1.996, 1.943, 1.985, 1.891, 1.993, 1.831, 1.93 ,
       1.601, 1.798, 2.   , 1.98 , 1.997, 1.998, 1.952, 1.938, 1.51 ,
       1.575, 1.676, 1.97 , 1.747, 2.   , 1.023, 2.   , 1.935, 2.   ,
       1.916, 1.191, 1.999, 1.84 , 1.896, 1.965, 1.227, 1.971, 1.027,
       2.   , 1.934, 1.915, 1.97 , 1.999, 1.973, 1.02 , 2.   , 1.997,
       1.991, 1.197, 1.741, 1.056])

In [61]:
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True, precision = 1)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')